image: gradle:6.6.0

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - node
            - gradle
          script:
            - gradle build
          after-script:
            - pipe: atlassian/checkstyle-report:0.2.0
      - step:
          name: Deploy to Heroku
          deployment: staging
          script:
            - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git HEAD
